services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: ecomm
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 10s
      retries: 5

  backend:
    build: ./backend
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/ecomm"
      JWT_SECRET: "your_super_secret_jwt_key"
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "node init_db.js && npm start"
    restart: always

volumes:
  pgdata: